'use client'

import { Template } from '@/types/card'

// 扩展模板库
export const templates: Template[] = [
  {
    id: 'minimal-business-1',
    name: '简约商务',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-business-1',
      name: '简约商务',
      width: 400,
      height: 600,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'avatar-1',
          type: 'image',
          x: 150,
          y: 40,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-1',
          type: 'text',
          x: 0,
          y: 160,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张三',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#1f2937',
          textAlign: 'center',
        },
        {
          id: 'title-1',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '高级产品经理',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#6b7280',
          textAlign: 'center',
        },
        {
          id: 'divider-1',
          type: 'divider',
          x: 50,
          y: 240,
          width: 300,
          height: 2,
          zIndex: 1,
          color: '#e5e7eb',
          thickness: 2,
        },
        {
          id: 'bio-1',
          type: 'text',
          x: 40,
          y: 260,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '专注于用户体验设计和产品创新。拥有10年互联网行业经验，热爱技术和设计。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#4b5563',
          textAlign: 'center',
        },
        {
          id: 'social-1',
          type: 'social',
          x: 100,
          y: 400,
          width: 200,
          height: 40,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'github', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
        {
          id: 'website-1',
          type: 'button',
          x: 120,
          y: 480,
          width: 160,
          height: 44,
          zIndex: 1,
          text: '访问网站',
          backgroundColor: '#0ea5e9',
          textColor: '#ffffff',
          borderRadius: 8,
          url: '',
        },
      ],
    },
  },
  {
    id: 'creative-artist-1',
    name: '创意艺术家',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'creative-artist-1',
      name: '创意艺术家',
      width: 400,
      height: 600,
      backgroundColor: '#fef3c7',
      elements: [
        {
          id: 'avatar-2',
          type: 'image',
          x: 140,
          y: 30,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-2',
          type: 'text',
          x: 0,
          y: 170,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李四',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#1f2937',
          textAlign: 'center',
        },
        {
          id: 'title-2',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '视觉设计师 / 插画师',
          fontSize: 18,
          fontWeight: 'medium',
          color: '#92400e',
          textAlign: 'center',
        },
        {
          id: 'bio-2',
          type: 'text',
          x: 40,
          y: 260,
          width: 320,
          height: 120,
          zIndex: 1,
          content: '热爱色彩与创意的自由灵魂。擅长插画设计、品牌视觉和创意策划。让我们一起用色彩点亮世界！🎨',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#78350f',
          textAlign: 'center',
        },
        {
          id: 'social-2',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 36,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'dark-tech-1',
    name: '科技黑',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'dark-tech-1',
      name: '科技黑',
      width: 400,
      height: 600,
      backgroundColor: '#0f172a',
      elements: [
        {
          id: 'avatar-3',
          type: 'image',
          x: 150,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 20,
        },
        {
          id: 'name-3',
          type: 'text',
          x: 0,
          y: 170,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王五',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#f1f5f9',
          textAlign: 'center',
        },
        {
          id: 'title-3',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '全栈工程师',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#94a3b8',
          textAlign: 'center',
        },
        {
          id: 'divider-3',
          type: 'divider',
          x: 50,
          y: 250,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#334155',
          thickness: 1,
        },
        {
          id: 'bio-3',
          type: 'text',
          x: 40,
          y: 270,
          width: 320,
          height: 80,
          zIndex: 1,
          content: '代码是诗，架构是画。专注于React、Node.js和云原生技术。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#cbd5e1',
          textAlign: 'center',
        },
        {
          id: 'social-3',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 40,
          zIndex: 1,
          platforms: [
            { platform: 'github', url: '' },
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'gradient-modern-1',
    name: '渐变现代',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'gradient-modern-1',
      name: '渐变现代',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      elements: [
        {
          id: 'name-4',
          type: 'text',
          x: 0,
          y: 80,
          width: 400,
          height: 50,
          zIndex: 1,
          content: '赵六',
          fontSize: 42,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-4',
          type: 'text',
          x: 0,
          y: 130,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '产品设计师',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'divider-4',
          type: 'divider',
          x: 100,
          y: 180,
          width: 200,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-4',
          type: 'text',
          x: 40,
          y: 200,
          width: 320,
          height: 120,
          zIndex: 1,
          content: '专注于创造优雅而实用的数字产品。相信设计可以改变世界，用简洁创造价值。',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-4',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 36,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'elegant-writer-1',
    name: '优雅作家',
    category: 'personal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'elegant-writer-1',
      name: '优雅作家',
      width: 400,
      height: 600,
      backgroundColor: '#fafafa',
      elements: [
        {
          id: 'avatar-5',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 10,
        },
        {
          id: 'name-5',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '孙七',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#1a1a1a',
          textAlign: 'center',
        },
        {
          id: 'title-5',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '作家 / 诗人',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#666666',
          textAlign: 'center',
        },
        {
          id: 'quote-5',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 80,
          zIndex: 1,
          content: '"文字是灵魂的镜子，我用手中的笔，映照心中的光。"',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#333333',
          textAlign: 'center',
        },
        {
          id: 'divider-5',
          type: 'divider',
          x: 50,
          y: 390,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#d4d4d4',
          thickness: 1,
        },
        {
          id: 'social-5',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'website', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'tech-blue-1',
    name: '科技蓝',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'tech-blue-1',
      name: '科技蓝',
      width: 400,
      height: 600,
      backgroundColor: '#2563eb',
      elements: [
        {
          id: 'avatar-6',
          type: 'image',
          x: 150,
          y: 60,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-6',
          type: 'text',
          x: 0,
          y: 180,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '周八',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-6',
          type: 'text',
          x: 0,
          y: 220,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '技术总监',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#93c5fd',
          textAlign: 'center',
        },
        {
          id: 'divider-6',
          type: 'divider',
          x: 50,
          y: 260,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#ffffff',
          thickness: 1,
        },
        {
          id: 'bio-6',
          type: 'text',
          x: 40,
          y: 280,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '15年技术经验，从初创公司到大型企业。相信技术改变世界，领导团队创造未来。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-6',
          type: 'social',
          x: 100,
          y: 420,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'nature-green-1',
    name: '自然绿',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'nature-green-1',
      name: '自然绿',
      width: 400,
      height: 600,
      backgroundColor: '#ecfdf5',
      elements: [
        {
          id: 'avatar-7',
          type: 'image',
          x: 130,
          y: 40,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-7',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '吴九',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#065f46',
          textAlign: 'center',
        },
        {
          id: 'title-7',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '环保设计师',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#047857',
          textAlign: 'center',
        },
        {
          id: 'bio-7',
          type: 'text',
          x: 40,
          y: 280,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '专注于可持续设计和环保产品。相信设计可以守护地球，用创意创造绿色未来。🌱',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#064e3b',
          textAlign: 'center',
        },
        {
          id: 'social-7',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'linkedin', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal-black-1',
    name: '极简黑',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-black-1',
      name: '极简黑',
      width: 400,
      height: 600,
      backgroundColor: '#000000',
      elements: [
        {
          id: 'avatar-8',
          type: 'image',
          x: 150,
          y: 100,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-8',
          type: 'text',
          x: 0,
          y: 220,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '郑十',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-8',
          type: 'text',
          x: 0,
          y: 260,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '独立开发者',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#888888',
          textAlign: 'center',
        },
        {
          id: 'divider-8',
          type: 'divider',
          x: 50,
          y: 300,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#333333',
          thickness: 1,
        },
        {
          id: 'social-8',
          type: 'social',
          x: 100,
          y: 350,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'linkedin', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'warm-orange-1',
    name: '温暖橙',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'warm-orange-1',
      name: '温暖橙',
      width: 400,
      height: 600,
      backgroundColor: '#fff7ed',
      elements: [
        {
          id: 'avatar-9',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-9',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王十一',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#9a3412',
          textAlign: 'center',
        },
        {
          id: 'title-9',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '用户体验研究员',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#c2410c',
          textAlign: 'center',
        },
        {
          id: 'bio-9',
          type: 'text',
          x: 40,
          y: 290,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '用温暖的心理解用户，用专业的态度解决问题。相信每个产品都应该有温度。🍊',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#7c2d12',
          textAlign: 'center',
        },
        {
          id: 'social-9',
          type: 'social',
          x: 80,
          y: 430,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'gradient-purple-1',
    name: '渐变紫',
    category: 'artistic',
    thumbnail: '',
    preview: '',
    config: {
      id: 'gradient-purple-1',
      name: '渐变紫',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(135deg, #a855f7 0%, #ec4899 100%)',
      elements: [
        {
          id: 'name-10',
          type: 'text',
          x: 0,
          y: 100,
          width: 400,
          height: 50,
          zIndex: 1,
          content: '李十二',
          fontSize: 42,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-10',
          type: 'text',
          x: 0,
          y: 150,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '艺术家 / 插画师',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'divider-10',
          type: 'divider',
          x: 80,
          y: 200,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-10',
          type: 'text',
          x: 40,
          y: 220,
          width: 320,
          height: 120,
          zIndex: 1,
          content: '用色彩描绘梦想，用线条勾勒未来。艺术是我的语言，世界是我的画布。🎨✨',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-10',
          type: 'social',
          x: 80,
          y: 400,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 36,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'classic-white-1',
    name: '经典白',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'classic-white-1',
      name: '经典白',
      width: 400,
      height: 600,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'avatar-11',
          type: 'image',
          x: 150,
          y: 60,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 10,
        },
        {
          id: 'name-11',
          type: 'text',
          x: 0,
          y: 180,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张十三',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#000000',
          textAlign: 'center',
        },
        {
          id: 'title-11',
          type: 'text',
          x: 0,
          y: 220,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '创始人 & CEO',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#666666',
          textAlign: 'center',
        },
        {
          id: 'divider-11',
          type: 'divider',
          x: 100,
          y: 260,
          width: 200,
          height: 2,
          zIndex: 1,
          color: '#000000',
          thickness: 2,
        },
        {
          id: 'bio-11',
          type: 'text',
          x: 40,
          y: 280,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '十年创业经验，从0到1创造价值。相信梦想的力量，用行动证明一切。',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#333333',
          textAlign: 'center',
        },
        {
          id: 'social-11',
          type: 'social',
          x: 100,
          y: 420,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'soft-pink-1',
    name: '柔和粉',
    category: 'personal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'soft-pink-1',
      name: '柔和粉',
      width: 400,
      height: 600,
      backgroundColor: '#fdf2f8',
      elements: [
        {
          id: 'avatar-12',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-12',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王十四',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#831843',
          textAlign: 'center',
        },
        {
          id: 'title-12',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '生活方式博主',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#9d174d',
          textAlign: 'center',
        },
        {
          id: 'bio-12',
          type: 'text',
          x: 40,
          y: 290,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '分享生活中的小确幸，记录美好的瞬间。热爱生活，热爱每一天。💕',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#701a75',
          textAlign: 'center',
        },
        {
          id: 'social-12',
          type: 'social',
          x: 80,
          y: 430,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'tech-dark-1',
    name: '科技深色',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'tech-dark-1',
      name: '科技深色',
      width: 400,
      height: 600,
      backgroundColor: '#1e293b',
      elements: [
        {
          id: 'avatar-13',
          type: 'image',
          x: 150,
          y: 80,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-13',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李十五',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#f1f5f9',
          textAlign: 'center',
        },
        {
          id: 'title-13',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: 'CTO',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#94a3b8',
          textAlign: 'center',
        },
        {
          id: 'divider-13',
          type: 'divider',
          x: 50,
          y: 280,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#475569',
          thickness: 1,
        },
        {
          id: 'bio-13',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '12年技术领导经验，构建技术团队，推动数字化转型。技术是我的信仰。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#e2e8f0',
          textAlign: 'center',
        },
        {
          id: 'social-13',
          type: 'social',
          x: 100,
          y: 440,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'creative-mix-1',
    name: '创意混色',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'creative-mix-1',
      name: '创意混色',
      width: 400,
      height: 600,
      backgroundColor: '#fef9c3',
      elements: [
        {
          id: 'avatar-14',
          type: 'image',
          x: 130,
          y: 40,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-14',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张十六',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#854d0e',
          textAlign: 'center',
        },
        {
          id: 'title-14',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '创意总监',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#a16207',
          textAlign: 'center',
        },
        {
          id: 'bio-14',
          type: 'text',
          x: 40,
          y: 280,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '创意是我的超能力，想象力是我的燃料。用不同颜色拼接世界，用独特视角诠释生活。🎭',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#713f12',
          textAlign: 'center',
        },
        {
          id: 'social-14',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'linkedin', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal-green-1',
    name: '极简绿',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-green-1',
      name: '极简绿',
      width: 400,
      height: 600,
      backgroundColor: '#10b981',
      elements: [
        {
          id: 'avatar-15',
          type: 'image',
          x: 150,
          y: 120,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-15',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李十七',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-15',
          type: 'text',
          x: 0,
          y: 280,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '独立顾问',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#a7f3d0',
          textAlign: 'center',
        },
        {
          id: 'divider-15',
          type: 'divider',
          x: 100,
          y: 320,
          width: 200,
          height: 1,
          zIndex: 1,
          color: '#ffffff',
          thickness: 1,
        },
        {
          id: 'social-15',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'professional-dark-1',
    name: '专业深色',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'professional-dark-1',
      name: '专业深色',
      width: 400,
      height: 600,
      backgroundColor: '#1e293b',
      elements: [
        {
          id: 'avatar-16',
          type: 'image',
          x: 140,
          y: 60,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-16',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张十八',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#f1f5f9',
          textAlign: 'center',
        },
        {
          id: 'title-16',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '产品负责人',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#94a3b8',
          textAlign: 'center',
        },
        {
          id: 'divider-16',
          type: 'divider',
          x: 50,
          y: 280,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#475569',
          thickness: 1,
        },
        {
          id: 'bio-16',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '8年产品经验，从0到1构建产品。注重用户体验和商业价值。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#cbd5e1',
          textAlign: 'center',
        },
        {
          id: 'social-16',
          type: 'social',
          x: 100,
          y: 430,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'gradient-warm-1',
    name: '温暖渐变',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'gradient-warm-1',
      name: '温暖渐变',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
      elements: [
        {
          id: 'avatar-17',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-17',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李十九',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-17',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '创意总监',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'divider-17',
          type: 'divider',
          x: 80,
          y: 300,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-17',
          type: 'text',
          x: 40,
          y: 320,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '创意是我的生活方式，灵感是我的工作动力。用热情创造价值。',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-17',
          type: 'social',
          x: 80,
          y: 450,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal-white-1',
    name: '极简白',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-white-1',
      name: '极简白',
      width: 400,
      height: 600,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'avatar-18',
          type: 'image',
          x: 150,
          y: 120,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 0,
        },
        {
          id: 'name-18',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王二十',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#000000',
          textAlign: 'center',
        },
        {
          id: 'title-18',
          type: 'text',
          x: 0,
          y: 280,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '独立开发者',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#666666',
          textAlign: 'center',
        },
        {
          id: 'divider-18',
          type: 'divider',
          x: 100,
          y: 320,
          width: 200,
          height: 2,
          zIndex: 1,
          color: '#000000',
          thickness: 2,
        },
        {
          id: 'social-18',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'linkedin', url: '' },
          ],
          iconSize: 28,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'business-blue-1',
    name: '商务蓝',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'business-blue-1',
      name: '商务蓝',
      width: 400,
      height: 600,
      backgroundColor: '#0284c7',
      elements: [
        {
          id: 'avatar-19',
          type: 'image',
          x: 140,
          y: 70,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-19',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '赵二十一',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-19',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '运营经理',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#e0f2fe',
          textAlign: 'center',
        },
        {
          id: 'divider-19',
          type: 'divider',
          x: 50,
          y: 290,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#ffffff',
          thickness: 1,
        },
        {
          id: 'bio-19',
          type: 'text',
          x: 40,
          y: 310,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '专注用户增长和数据分析。10年运营经验，从0到100万+用户。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#e0f2fe',
          textAlign: 'center',
        },
        {
          id: 'social-19',
          type: 'social',
          x: 100,
          y: 440,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'artist-color-1',
    name: '艺术家色彩',
    category: 'artistic',
    thumbnail: '',
    preview: '',
    config: {
      id: 'artist-color-1',
      name: '艺术家色彩',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(45deg, #f97316 0%, #fbbf24 25%, #34d399 50%, #3b82f6 75%, #8b5cf6 100%)',
      elements: [
        {
          id: 'name-20',
          type: 'text',
          x: 0,
          y: 100,
          width: 400,
          height: 50,
          zIndex: 1,
          content: '李二十二',
          fontSize: 42,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-20',
          type: 'text',
          x: 0,
          y: 150,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '视觉艺术家',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'divider-20',
          type: 'divider',
          x: 80,
          y: 200,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-20',
          type: 'text',
          x: 40,
          y: 220,
          width: 320,
          height: 140,
          zIndex: 1,
          content: '色彩是我的语言，艺术是我的生命。用鲜艳的笔触描绘世界的美好，用独特的视角诠释生活的意义。🎨🌈',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-20',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal-gray-1',
    name: '极简灰',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-gray-1',
      name: '极简灰',
      width: 400,
      height: 600,
      backgroundColor: '#f3f4f6',
      elements: [
        {
          id: 'avatar-21',
          type: 'image',
          x: 140,
          y: 100,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-21',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '周二十三',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#1f2937',
          textAlign: 'center',
        },
        {
          id: 'title-21',
          type: 'text',
          x: 0,
          y: 280,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '技术顾问',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#6b7280',
          textAlign: 'center',
        },
        {
          id: 'divider-21',
          type: 'divider',
          x: 100,
          y: 320,
          width: 200,
          height: 1,
          zIndex: 1,
          color: '#9ca3af',
          thickness: 1,
        },
        {
          id: 'social-21',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
          ],
          iconSize: 28,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'personal-warm-1',
    name: '个人温暖',
    category: 'personal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'personal-warm-1',
      name: '个人温暖',
      width: 400,
      height: 600,
      backgroundColor: '#fff7ed',
      elements: [
        {
          id: 'avatar-22',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-22',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王二十四',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#9a3412',
          textAlign: 'center',
        },
        {
          id: 'title-22',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '生活博主',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#c2410c',
          textAlign: 'center',
        },
        {
          id: 'bio-22',
          type: 'text',
          x: 40,
          y: 290,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '分享生活中的小确幸，记录美好的瞬间。热爱生活，热爱每一天，用文字传递温暖。☀️',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#7c2d12',
          textAlign: 'center',
        },
        {
          id: 'divider-22',
          type: 'divider',
          x: 50,
          y: 400,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#d4d4d4',
          thickness: 1,
        },
        {
          id: 'social-22',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'creative-purple-1',
    name: '创意紫',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'creative-purple-1',
      name: '创意紫',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(135deg, #a855f7 0%, #6366f1 100%)',
      elements: [
        {
          id: 'avatar-23',
          type: 'image',
          x: 130,
          y: 40,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-23',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张二十五',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-23',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '品牌设计师',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#f3f4f6',
          textAlign: 'center',
        },
        {
          id: 'divider-23',
          type: 'divider',
          x: 80,
          y: 280,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-23',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '用创意讲述品牌故事，用设计传递品牌价值。相信创意可以改变世界，用设计连接人心。',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#e5e7eb',
          textAlign: 'center',
        },
        {
          id: 'social-23',
          type: 'social',
          x: 80,
          y: 430,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'instagram', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'business-modern-1',
    name: '商务现代',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'business-modern-1',
      name: '商务现代',
      width: 400,
      height: 600,
      backgroundColor: '#1e3a8a',
      elements: [
        {
          id: 'avatar-24',
          type: 'image',
          x: 140,
          y: 60,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-24',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李二十六',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-24',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '技术总监',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#93c5fd',
          textAlign: 'center',
        },
        {
          id: 'divider-24',
          type: 'divider',
          x: 50,
          y: 280,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#60a5fa',
          thickness: 1,
        },
        {
          id: 'bio-24',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '12年技术领导经验，从初创公司到大型企业。推动技术变革，引领团队创新。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#e2e8f0',
          textAlign: 'center',
        },
        {
          id: 'social-24',
          type: 'social',
          x: 100,
          y: 430,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'github', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'artistic-abstract-1',
    name: '艺术抽象',
    category: 'artistic',
    thumbnail: '',
    preview: '',
    config: {
      id: 'artistic-abstract-1',
      name: '艺术抽象',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(180deg, #2d1b69 0%, #713f12 50%, #1a1a2e 100%)',
      elements: [
        {
          id: 'name-25',
          type: 'text',
          x: 0,
          y: 100,
          width: 400,
          height: 50,
          zIndex: 1,
          content: '周二十七',
          fontSize: 42,
          fontWeight: 'bold',
          color: '#fcd34d',
          textAlign: 'center',
        },
        {
          id: 'title-25',
          type: 'text',
          x: 0,
          y: 150,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '数字艺术家',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#fbbf24',
          textAlign: 'center',
        },
        {
          id: 'divider-25',
          type: 'divider',
          x: 50,
          y: 200,
          width: 300,
          height: 2,
          zIndex: 1,
          color: '#fcd34d',
          thickness: 2,
        },
        {
          id: 'bio-25',
          type: 'text',
          x: 40,
          y: 220,
          width: 320,
          height: 140,
          zIndex: 1,
          content: '数字是我的画布，代码是我的画笔。在虚拟世界创造真实的感动，用抽象艺术诠释数字时代。',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#fde68a',
          textAlign: 'center',
        },
        {
          id: 'social-25',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'minimal-clean-1',
    name: '极简清爽',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-clean-1',
      name: '极简清爽',
      width: 400,
      height: 600,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'avatar-26',
          type: 'image',
          x: 150,
          y: 120,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-26',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王二十八',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#000000',
          textAlign: 'center',
        },
        {
          id: 'title-26',
          type: 'text',
          x: 0,
          y: 280,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '全栈开发',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#666666',
          textAlign: 'center',
        },
        {
          id: 'divider-26',
          type: 'divider',
          x: 100,
          y: 320,
          width: 200,
          height: 2,
          zIndex: 1,
          color: '#000000',
          thickness: 2,
        },
        {
          id: 'social-26',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'github', url: '' },
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
          ],
          iconSize: 28,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'personal-nature-1',
    name: '自然个人',
    category: 'personal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'personal-nature-1',
      name: '自然个人',
      width: 400,
      height: 600,
      backgroundColor: '#f0fdf4',
      elements: [
        {
          id: 'avatar-27',
          type: 'image',
          x: 130,
          y: 50,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-27',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张二十九',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#166534',
          textAlign: 'center',
        },
        {
          id: 'title-27',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '自然爱好者',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#15803d',
          textAlign: 'center',
        },
        {
          id: 'bio-27',
          type: 'text',
          x: 40,
          y: 290,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '热爱大自然，保护环境。用镜头记录美好，用行动守护地球。让我们的世界更美好。🌱',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#14532d',
          textAlign: 'center',
        },
        {
          id: 'social-27',
          type: 'social',
          x: 80,
          y: 430,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'gradient-pink-1',
    name: '渐变粉',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'gradient-pink-1',
      name: '渐变粉',
      width: 400,
      height: 600,
      backgroundColor: 'linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%)',
      elements: [
        {
          id: 'name-28',
          type: 'text',
          x: 0,
          y: 100,
          width: 400,
          height: 50,
          zIndex: 1,
          content: '李三十',
          fontSize: 42,
          fontWeight: 'bold',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'title-28',
          type: 'text',
          x: 0,
          y: 150,
          width: 400,
          height: 30,
          zIndex: 1,
          content: '生活方式创作者',
          fontSize: 20,
          fontWeight: 'normal',
          color: '#f3f4f6',
          textAlign: 'center',
        },
        {
          id: 'divider-28',
          type: 'divider',
          x: 80,
          y: 200,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#ffffff',
          thickness: 2,
        },
        {
          id: 'bio-28',
          type: 'text',
          x: 40,
          y: 220,
          width: 320,
          height: 120,
          zIndex: 1,
          content: '用粉色传递温暖，用创意点亮生活。分享美好的瞬间，记录快乐的时光。💕✨',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#ffffff',
          textAlign: 'center',
        },
        {
          id: 'social-28',
          type: 'social',
          x: 80,
          y: 400,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'youtube', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 28,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'business-clean-1',
    name: '商务清爽',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'business-clean-1',
      name: '商务清爽',
      width: 400,
      height: 600,
      backgroundColor: '#f8fafc',
      elements: [
        {
          id: 'avatar-29',
          type: 'image',
          x: 140,
          y: 70,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-29',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '周三十一',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#1e293b',
          textAlign: 'center',
        },
        {
          id: 'title-29',
          type: 'text',
          x: 0,
          y: 250,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '高级顾问',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#64748b',
          textAlign: 'center',
        },
        {
          id: 'divider-29',
          type: 'divider',
          x: 50,
          y: 290,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#cbd5e1',
          thickness: 1,
        },
        {
          id: 'bio-29',
          type: 'text',
          x: 40,
          y: 310,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '15年行业经验，为企业提供战略咨询。用专业赢得信任，用价值创造未来。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#475569',
          textAlign: 'center',
        },
        {
          id: 'social-29',
          type: 'social',
          x: 100,
          y: 430,
          width: 200,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'artistic-vintage-1',
    name: '艺术复古',
    category: 'artistic',
    thumbnail: '',
    preview: '',
    config: {
      id: 'artistic-vintage-1',
      name: '艺术复古',
      width: 400,
      height: 600,
      backgroundColor: '#fef9c3',
      elements: [
        {
          id: 'avatar-30',
          type: 'image',
          x: 130,
          y: 40,
          width: 140,
          height: 140,
          zIndex: 1,
          src: 'https://via.placeholder.com/140',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-30',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王三十二',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#92400e',
          textAlign: 'center',
        },
        {
          id: 'title-30',
          type: 'text',
          x: 0,
          y: 240,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '复古设计师',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#b45309',
          textAlign: 'center',
        },
        {
          id: 'divider-30',
          type: 'divider',
          x: 80,
          y: 280,
          width: 240,
          height: 2,
          zIndex: 1,
          color: '#92400e',
          thickness: 2,
        },
        {
          id: 'bio-30',
          type: 'text',
          x: 40,
          y: 300,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '用复古的视角诠释现代设计，用经典的语言讲述新的故事。传承经典，创新未来。',
          fontSize: 15,
          fontWeight: 'normal',
          color: '#78350f',
          textAlign: 'center',
        },
        {
          id: 'social-30',
          type: 'social',
          x: 80,
          y: 430,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
]

export function getTemplatesByCategory(category: Template['category']) {
  return templates.filter((t) => t.category === category)
}

export function getTemplateById(id: string) {
  return templates.find((t) => t.id === id)
}
