import { Template } from '@/types/card'

// 示例模板数据
export const templates: Template[] = [
  {
    id: 'minimal-business-1',
    name: '简约商务',
    category: 'business',
    thumbnail: '',
    preview: '',
    config: {
      id: 'minimal-business-1',
      name: '简约商务',
      width: 400,
      height: 600,
      backgroundColor: '#ffffff',
      elements: [
        {
          id: 'avatar-1',
          type: 'image',
          x: 150,
          y: 40,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 50,
        },
        {
          id: 'name-1',
          type: 'text',
          x: 0,
          y: 160,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '张三',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#1f2937',
          textAlign: 'center',
        },
        {
          id: 'title-1',
          type: 'text',
          x: 0,
          y: 200,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '高级产品经理',
          fontSize: 18,
          fontWeight: 'normal',
          color: '#6b7280',
          textAlign: 'center',
        },
        {
          id: 'divider-1',
          type: 'divider',
          x: 50,
          y: 240,
          width: 300,
          height: 2,
          zIndex: 1,
          color: '#e5e7eb',
          thickness: 2,
        },
        {
          id: 'bio-1',
          type: 'text',
          x: 40,
          y: 260,
          width: 320,
          height: 100,
          zIndex: 1,
          content: '专注于用户体验设计和产品创新。拥有10年互联网行业经验，热爱技术和设计。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#4b5563',
          textAlign: 'center',
        },
        {
          id: 'social-1',
          type: 'social',
          x: 100,
          y: 400,
          width: 200,
          height: 40,
          zIndex: 1,
          platforms: [
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'github', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
        {
          id: 'website-1',
          type: 'button',
          x: 120,
          y: 480,
          width: 160,
          height: 44,
          zIndex: 1,
          text: '访问网站',
          backgroundColor: '#0ea5e9',
          textColor: '#ffffff',
          borderRadius: 8,
          url: '',
        },
      ],
    },
  },
  {
    id: 'creative-artist-1',
    name: '创意艺术家',
    category: 'creative',
    thumbnail: '',
    preview: '',
    config: {
      id: 'creative-artist-1',
      name: '创意艺术家',
      width: 400,
      height: 600,
      backgroundColor: '#fef3c7',
      elements: [
        {
          id: 'avatar-2',
          type: 'image',
          x: 140,
          y: 30,
          width: 120,
          height: 120,
          zIndex: 1,
          src: 'https://via.placeholder.com/120',
          alt: '头像',
          borderRadius: 60,
        },
        {
          id: 'name-2',
          type: 'text',
          x: 0,
          y: 170,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '李四',
          fontSize: 36,
          fontWeight: 'bold',
          color: '#1f2937',
          textAlign: 'center',
        },
        {
          id: 'title-2',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '视觉设计师 / 插画师',
          fontSize: 18,
          fontWeight: 'medium',
          color: '#92400e',
          textAlign: 'center',
        },
        {
          id: 'bio-2',
          type: 'text',
          x: 40,
          y: 260,
          width: 320,
          height: 120,
          zIndex: 1,
          content: '热爱色彩与创意的自由灵魂。擅长插画设计、品牌视觉和创意策划。让我们一起用色彩点亮世界！🎨',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#78350f',
          textAlign: 'center',
        },
        {
          id: 'social-2',
          type: 'social',
          x: 80,
          y: 420,
          width: 240,
          height: 50,
          zIndex: 1,
          platforms: [
            { platform: 'instagram', url: '' },
            { platform: 'twitter', url: '' },
            { platform: 'website', url: '' },
            { platform: 'email', url: '' },
          ],
          iconSize: 36,
          iconSpacing: 24,
          alignment: 'center',
        },
      ],
    },
  },
  {
    id: 'dark-tech-1',
    name: '科技黑',
    category: 'minimal',
    thumbnail: '',
    preview: '',
    config: {
      id: 'dark-tech-1',
      name: '科技黑',
      width: 400,
      height: 600,
      backgroundColor: '#0f172a',
      elements: [
        {
          id: 'avatar-3',
          type: 'image',
          x: 150,
          y: 50,
          width: 100,
          height: 100,
          zIndex: 1,
          src: 'https://via.placeholder.com/100',
          alt: '头像',
          borderRadius: 20,
        },
        {
          id: 'name-3',
          type: 'text',
          x: 0,
          y: 170,
          width: 400,
          height: 40,
          zIndex: 1,
          content: '王五',
          fontSize: 32,
          fontWeight: 'bold',
          color: '#f1f5f9',
          textAlign: 'center',
        },
        {
          id: 'title-3',
          type: 'text',
          x: 0,
          y: 210,
          width: 400,
          height: 24,
          zIndex: 1,
          content: '全栈工程师',
          fontSize: 16,
          fontWeight: 'normal',
          color: '#94a3b8',
          textAlign: 'center',
        },
        {
          id: 'divider-3',
          type: 'divider',
          x: 50,
          y: 250,
          width: 300,
          height: 1,
          zIndex: 1,
          color: '#334155',
          thickness: 1,
        },
        {
          id: 'bio-3',
          type: 'text',
          x: 40,
          y: 270,
          width: 320,
          height: 80,
          zIndex: 1,
          content: '代码是诗，架构是画。专注于React、Node.js和云原生技术。',
          fontSize: 14,
          fontWeight: 'normal',
          color: '#cbd5e1',
          textAlign: 'center',
        },
        {
          id: 'social-3',
          type: 'social',
          x: 100,
          y: 380,
          width: 200,
          height: 40,
          zIndex: 1,
          platforms: [
            { platform: 'github', url: '' },
            { platform: 'linkedin', url: '' },
            { platform: 'twitter', url: '' },
          ],
          iconSize: 32,
          iconSpacing: 20,
          alignment: 'center',
        },
      ],
    },
  },
]

export function getTemplatesByCategory(category: Template['category']) {
  return templates.filter((t) => t.category === category)
}

export function getTemplateById(id: string) {
  return templates.find((t) => t.id === id)
}
